#!/bin/sh
# Muestra los rangos IP de un AS
# (c) hackingyseguridad.com 2017
# Uso: ./bgp2ip AS
echo Uso: ./bgp2ip AS

AS_NUMBER=$1

echo "Rangos IPv4 para AS$AS_NUMBER:"
whois -h whois.radb.net -- '-i origin AS'$AS_NUMBER | grep '^route:' | awk '{print $2}'

echo "\nRangos IPv6 para AS$AS_NUMBER:"
whois -h whois.radb.net -- '-i origin AS'$AS_NUMBER | grep '^route6:' | awk '{print $2}'

