#!/bin/sh
# Esaneo de puertos/servicios rapido sobre IP, rango o fqdn en fichero todas.txt.
# (r) hackingyseguridad.com 2025
echo
echo "..."
cat << "INFO"

(:`--..___...-''``-._             |`._
  ```--...--.      . `-..__      .`/ _\  
            `\     '       ```--`.    />
            : :   :               `:`-'
             `.:.  `.._--...___     ``--...__      
                ``--..,)       ```----....__,)   http://www.hackingyseguridad.com

INFO
if [ -z "$1" ]; then
        echo
        echo "Esaneo rapido de puertos/servicios, IP, rango o fqdn"
        echo "Requiere nmap y listado de IP, todas.txt"
        echo "Uso.: sh scanpuerto <puerto1,puerto2>"
        echo
        exit 0
fi
echo
echo
nmap -e eth0 -Pn -iL todas.txt --open -n -p$1 --randomize-hosts --defeat-rst-ratelimit --max-retries 2 --host-timeout 99s  --min-rate 99  -oG resultado.txt 
