#!/bin/sh
# Zmap https://github.com/zmap/zmap 
# Esaneo de puertos/servicios rapido sobre IP, rango o fqdn en fichero todas.txt.
# Escanea 100000 activos en una hora, pero puede tener una fiabilidad del 50%.
# Para maxima velocidad añadir el parametro  --bandwidth=999
# (R) hackingyseguridad.com 2025
echo
echo "..."
cat << "INFO"

(:`--..___...-''``-._             |`._
  ```--...--.      . `-..__      .`/ _\  
            `\     '       ```--`.    />
            : :   :    zmap      `:`-'
             `.:.  `.._--...___     ``--...__      
                ``--..,)       ```----....__,)   http://www.hackingyseguridad.com

INFO
if [ -z "$1" ]; then
        echo
        echo "Esaneo rapido de puertos/servicios, IP, rango" 
        echo "Requiere Zmap y listado de IP, todas.txt"
        echo "Uso.: sh scanpuerto1 <puerto1,puerto2>"
        echo
        exit 0
fi
echo
echo
mv /etc/zmap/zmap.conf /etc/zmap/zmap.conf.bk
mv /etc/zmap/blocklist.conf  /etc/zmap/blocklist.conf.bk
echo
zmap --bandwidth=9M -p $1 --verbosity=0 -w todas.txt -o resultado.txt
