#!/bin/bash
# Traceroute AS 

if [[ -z "$1" ]]
then
	echo "IP: $0 Host";
	exit 1;
fi

OIFS=$IFS;
IFS=$'\n';
for line in $( traceroute  -A "$1" )
do
	echo "$line" | grep "AS" -q;
	if [ $? -eq 0 ]
	then
		AS=$( echo $line | grep -E "\[AS.+?\] " -o | tr -d  "[]" | cut -d " " -f1 );
		ASResult=$( whois -h whois.cymru.com " -v $AS" | tail -n 1 | cut -d "|" -f 5 );
		echo "$line" | sed "s/\]/:$ASResult\]/1";
 
	else
		echo "$line";
	fi	

done
IFS=$OIFS;

